### ISSUE TITLE
Having issues with google domain

### ISSUE THREAD

**Issue by aburke20** [RooneyMcNibNug/pihole-stuff#21] opened 2020-06-23 19:08 UTC
Since the last few days I've been having issues watching Youtube videos on my phone.

I tracked it down to this blocklist, and the _semanticlocation-pa.googleapis.com_ domaine.

Is that something that will get updated/fix, or that I need to disable from now on ?

similarly, with all variations of:
rX---sn-XXXXXXX.googlevideo.com , from a different blocklist.

Just trying to figure out what I should whitelist,
Thanks.

**Comment by RooneyMcNibNug** [comment] 2020-06-24 22:30
Hi - thank you for the ticket here.

I have gone ahead and removed `semanticlocation-pa.googleapis.com` from my list for now. I believe this is a part of google's user location API, which I _do_ find invasive, but I am willing to remove this single domain from my list to make it easy for people to block the thousands of others on the list without having to whitelist something on their end.

Let me know if this helps your video issue, please? I'm eager to know if it is the root cause.

**Comment by RooneyMcNibNug** [comment] 2020-06-29 16:33
Going to close this now, but let me know if you have any other issues @aburke20 .

**Closed by RooneyMcNibNug** 2020-06-29 16:33 UTC
